### ISSUE TITLE
QC to make sure commits since January are present in new Ember app

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-octane-vs-classic-cheat-sheet#34]

**Comment by ijlee2** [comment]
I checked the [commit history since January 1, 2020](https://github.com/ember-learn/ember-octane-vs-classic-cheat-sheet/commits/master?after=9eb0978badd6357c3f56b1baec5ab8541b1f60f2+69&branch=master).

I think the only commit that could have been affected was https://github.com/ember-learn/ember-octane-vs-classic-cheat-sheet/commit/bcc6e38acd225d7a049d212d0b86c6873a4c5eae. I checked that the code changes do appear in the Ember app at https://github.com/ember-learn/ember-octane-vs-classic-cheat-sheet/blob/master/snippets/component-lifecycle/constructors/octane.js#L4-L5.
